name: JSDoc
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: JsDoc
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: /src
          recurse: true
          output_dir: /out