name: JSDoc2
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches: [ main ]

jobs:
  build:
    # Job name is Greeting
    name: JsDoc
    # This job runs on Linux
    #runs-on: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./src
          recurse: true
          output_dir: ./out
          template: minami
          front_page: README.md

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.6.4
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./out